development:
  adapter: postgresql
  database: golden_pheasant_development
  pool: 5
  timeout: 5000
  user: nick
test:
  adapter: postgresql
  database: golden_pheasant_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: golden_pheasant_production
  pool: 5
  timeout: 5000
